[2021-03-19 12:29:42] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function App\Http\Controllers\SecretApi::getSecretByHash(), 0 passed and exactly 1 expected in /data/secret/app/Http/Controllers/SecretApi.php:72
Stack trace:
#0 [internal function]: App\Http\Controllers\SecretApi->getSecretByHash()
#1 /data/secret/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#2 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(603): Illuminate\Container\Container->call(Array, Array)
#3 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(569): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#4 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SecretApi), 'getSecretByHash', Array)
#5 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#6 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#7 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(393): Laravel\Lumen\Application->handleFoundRoute(Array)
#8 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#9 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#10 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#11 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#12 {main}  
[2021-03-19 12:31:19] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function App\Http\Controllers\SecretApi::getSecretByHash(), 0 passed and exactly 1 expected in /data/secret/app/Http/Controllers/SecretApi.php:72
Stack trace:
#0 [internal function]: App\Http\Controllers\SecretApi->getSecretByHash()
#1 /data/secret/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#2 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(603): Illuminate\Container\Container->call(Array, Array)
#3 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(569): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#4 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SecretApi), 'getSecretByHash', Array)
#5 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#6 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#7 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(393): Laravel\Lumen\Application->handleFoundRoute(Array)
#8 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#9 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#10 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#11 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#12 {main}  
[2021-03-19 12:31:28] lumen.ERROR: PDOException: SQLSTATE[HY000] [2002] Connection refused in /data/secret/vendor/illuminate/database/Connectors/Connector.php:55
Stack trace:
#0 /data/secret/vendor/illuminate/database/Connectors/Connector.php(55): PDO->__construct('mysql:host=mysq...', 'root', 'root', Array)
#1 /data/secret/vendor/illuminate/database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=mysq...', Array, Array)
#2 /data/secret/vendor/illuminate/database/Connectors/ConnectionFactory.php(61): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#4 /data/secret/vendor/illuminate/database/Connection.php(924): call_user_func(Object(Closure))
#5 /data/secret/vendor/illuminate/database/Connection.php(792): Illuminate\Database\Connection->getPdo()
#6 /data/secret/vendor/illuminate/database/Connection.php(677): Illuminate\Database\Connection->reconnectIfMissingConnection()
#7 /data/secret/vendor/illuminate/database/Connection.php(349): Illuminate\Database\Connection->run('SELECT * FROM s...', Array, Object(Closure))
#8 [internal function]: Illuminate\Database\Connection->select('SELECT * FROM s...')
#9 /data/secret/vendor/illuminate/database/DatabaseManager.php(317): call_user_func_array(Array, Array)
#10 /data/secret/app/Http/Controllers/SecretApi.php(78): Illuminate\Database\DatabaseManager->__call('select', Array)
#11 [internal function]: App\Http\Controllers\SecretApi->getSecretByHash()
#12 /data/secret/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#13 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(603): Illuminate\Container\Container->call(Array, Array)
#14 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(569): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#15 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SecretApi), 'getSecretByHash', Array)
#16 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#17 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#18 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(393): Laravel\Lumen\Application->handleFoundRoute(Array)
#19 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#20 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#21 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#22 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#23 {main}  
[2021-03-19 12:32:11] lumen.ERROR: PDOException: SQLSTATE[HY000] [2002] Connection refused in /data/secret/vendor/illuminate/database/Connectors/Connector.php:55
Stack trace:
#0 /data/secret/vendor/illuminate/database/Connectors/Connector.php(55): PDO->__construct('mysql:host=mysq...', 'root', 'root', Array)
#1 /data/secret/vendor/illuminate/database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=mysq...', Array, Array)
#2 /data/secret/vendor/illuminate/database/Connectors/ConnectionFactory.php(61): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#4 /data/secret/vendor/illuminate/database/Connection.php(924): call_user_func(Object(Closure))
#5 /data/secret/vendor/illuminate/database/Connection.php(792): Illuminate\Database\Connection->getPdo()
#6 /data/secret/vendor/illuminate/database/Connection.php(677): Illuminate\Database\Connection->reconnectIfMissingConnection()
#7 /data/secret/vendor/illuminate/database/Connection.php(349): Illuminate\Database\Connection->run('SELECT * FROM s...', Array, Object(Closure))
#8 [internal function]: Illuminate\Database\Connection->select('SELECT * FROM s...')
#9 /data/secret/vendor/illuminate/database/DatabaseManager.php(317): call_user_func_array(Array, Array)
#10 /data/secret/app/Http/Controllers/SecretApi.php(78): Illuminate\Database\DatabaseManager->__call('select', Array)
#11 [internal function]: App\Http\Controllers\SecretApi->getSecretByHash('asdasd')
#12 /data/secret/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#13 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(603): Illuminate\Container\Container->call(Array, Array)
#14 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(569): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#15 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SecretApi), 'getSecretByHash', Array)
#16 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#17 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#18 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(466): Laravel\Lumen\Application->handleFoundRoute(Array)
#19 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(397): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#20 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#21 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#22 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#23 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#24 {main}  
[2021-03-19 12:32:31] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined function App\Http\Controllers\dump() in /data/secret/app/Http/Controllers/SecretApi.php:77
Stack trace:
#0 [internal function]: App\Http\Controllers\SecretApi->getSecretByHash('asdasd')
#1 /data/secret/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#2 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(603): Illuminate\Container\Container->call(Array, Array)
#3 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(569): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#4 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SecretApi), 'getSecretByHash', Array)
#5 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#6 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#7 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(466): Laravel\Lumen\Application->handleFoundRoute(Array)
#8 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(397): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#9 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#10 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#11 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#12 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#13 {main}  
[2021-03-19 12:32:41] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined function App\Http\Controllers\dump() in /data/secret/app/Http/Controllers/SecretApi.php:77
Stack trace:
#0 [internal function]: App\Http\Controllers\SecretApi->getSecretByHash('asdasd')
#1 /data/secret/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#2 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(603): Illuminate\Container\Container->call(Array, Array)
#3 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(569): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#4 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SecretApi), 'getSecretByHash', Array)
#5 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#6 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#7 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(466): Laravel\Lumen\Application->handleFoundRoute(Array)
#8 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(397): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#9 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#10 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#11 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#12 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#13 {main}  
[2021-03-19 12:32:43] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined function App\Http\Controllers\dump() in /data/secret/app/Http/Controllers/SecretApi.php:77
Stack trace:
#0 [internal function]: App\Http\Controllers\SecretApi->getSecretByHash('asdasd')
#1 /data/secret/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#2 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(603): Illuminate\Container\Container->call(Array, Array)
#3 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(569): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#4 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SecretApi), 'getSecretByHash', Array)
#5 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#6 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#7 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(466): Laravel\Lumen\Application->handleFoundRoute(Array)
#8 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(397): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#9 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#10 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#11 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#12 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#13 {main}  
[2021-03-19 12:33:39] lumen.ERROR: PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'secret.secret' doesn't exist in /data/secret/vendor/illuminate/database/Connection.php:333
Stack trace:
#0 /data/secret/vendor/illuminate/database/Connection.php(333): PDO->prepare('SELECT * FROM s...')
#1 /data/secret/vendor/illuminate/database/Connection.php(722): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'SELECT * FROM s...', Array)
#2 /data/secret/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback('SELECT * FROM s...', Array, Object(Closure))
#3 /data/secret/vendor/illuminate/database/Connection.php(349): Illuminate\Database\Connection->run('SELECT * FROM s...', Array, Object(Closure))
#4 [internal function]: Illuminate\Database\Connection->select('SELECT * FROM s...')
#5 /data/secret/vendor/illuminate/database/DatabaseManager.php(317): call_user_func_array(Array, Array)
#6 /data/secret/app/Http/Controllers/SecretApi.php(78): Illuminate\Database\DatabaseManager->__call('select', Array)
#7 [internal function]: App\Http\Controllers\SecretApi->getSecretByHash('asdasd')
#8 /data/secret/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#9 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(603): Illuminate\Container\Container->call(Array, Array)
#10 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(569): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#11 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SecretApi), 'getSecretByHash', Array)
#12 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#13 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#14 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(466): Laravel\Lumen\Application->handleFoundRoute(Array)
#15 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(397): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#16 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#17 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#18 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#19 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#20 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'secret.secret' doesn't exist (SQL: SELECT * FROM secret) in /data/secret/vendor/illuminate/database/Connection.php:729
Stack trace:
#0 /data/secret/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback('SELECT * FROM s...', Array, Object(Closure))
#1 /data/secret/vendor/illuminate/database/Connection.php(349): Illuminate\Database\Connection->run('SELECT * FROM s...', Array, Object(Closure))
#2 [internal function]: Illuminate\Database\Connection->select('SELECT * FROM s...')
#3 /data/secret/vendor/illuminate/database/DatabaseManager.php(317): call_user_func_array(Array, Array)
#4 /data/secret/app/Http/Controllers/SecretApi.php(78): Illuminate\Database\DatabaseManager->__call('select', Array)
#5 [internal function]: App\Http\Controllers\SecretApi->getSecretByHash('asdasd')
#6 /data/secret/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#7 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(603): Illuminate\Container\Container->call(Array, Array)
#8 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(569): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#9 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SecretApi), 'getSecretByHash', Array)
#10 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#11 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#12 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(466): Laravel\Lumen\Application->handleFoundRoute(Array)
#13 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(397): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#14 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#15 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#16 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#17 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#18 {main}  
[2021-03-19 12:35:27] lumen.ERROR: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hash' in 'where clause' in /data/secret/vendor/illuminate/database/Connection.php:333
Stack trace:
#0 /data/secret/vendor/illuminate/database/Connection.php(333): PDO->prepare('SELECT * FROM s...')
#1 /data/secret/vendor/illuminate/database/Connection.php(722): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'SELECT * FROM s...', Array)
#2 /data/secret/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback('SELECT * FROM s...', Array, Object(Closure))
#3 /data/secret/vendor/illuminate/database/Connection.php(349): Illuminate\Database\Connection->run('SELECT * FROM s...', Array, Object(Closure))
#4 [internal function]: Illuminate\Database\Connection->select('SELECT * FROM s...', Array)
#5 /data/secret/vendor/illuminate/database/DatabaseManager.php(317): call_user_func_array(Array, Array)
#6 /data/secret/app/Http/Controllers/SecretApi.php(78): Illuminate\Database\DatabaseManager->__call('select', Array)
#7 [internal function]: App\Http\Controllers\SecretApi->getSecretByHash('asdasd')
#8 /data/secret/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#9 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(603): Illuminate\Container\Container->call(Array, Array)
#10 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(569): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#11 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SecretApi), 'getSecretByHash', Array)
#12 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#13 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#14 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(466): Laravel\Lumen\Application->handleFoundRoute(Array)
#15 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(397): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#16 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#17 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#18 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#19 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#20 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hash' in 'where clause' (SQL: SELECT * FROM secrets where hash = asdasd) in /data/secret/vendor/illuminate/database/Connection.php:729
Stack trace:
#0 /data/secret/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback('SELECT * FROM s...', Array, Object(Closure))
#1 /data/secret/vendor/illuminate/database/Connection.php(349): Illuminate\Database\Connection->run('SELECT * FROM s...', Array, Object(Closure))
#2 [internal function]: Illuminate\Database\Connection->select('SELECT * FROM s...', Array)
#3 /data/secret/vendor/illuminate/database/DatabaseManager.php(317): call_user_func_array(Array, Array)
#4 /data/secret/app/Http/Controllers/SecretApi.php(78): Illuminate\Database\DatabaseManager->__call('select', Array)
#5 [internal function]: App\Http\Controllers\SecretApi->getSecretByHash('asdasd')
#6 /data/secret/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#7 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(603): Illuminate\Container\Container->call(Array, Array)
#8 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(569): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#9 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SecretApi), 'getSecretByHash', Array)
#10 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#11 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#12 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(466): Laravel\Lumen\Application->handleFoundRoute(Array)
#13 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(397): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#14 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#15 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#16 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#17 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#18 {main}  
[2021-03-19 12:35:29] lumen.ERROR: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hash' in 'where clause' in /data/secret/vendor/illuminate/database/Connection.php:333
Stack trace:
#0 /data/secret/vendor/illuminate/database/Connection.php(333): PDO->prepare('SELECT * FROM s...')
#1 /data/secret/vendor/illuminate/database/Connection.php(722): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'SELECT * FROM s...', Array)
#2 /data/secret/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback('SELECT * FROM s...', Array, Object(Closure))
#3 /data/secret/vendor/illuminate/database/Connection.php(349): Illuminate\Database\Connection->run('SELECT * FROM s...', Array, Object(Closure))
#4 [internal function]: Illuminate\Database\Connection->select('SELECT * FROM s...', Array)
#5 /data/secret/vendor/illuminate/database/DatabaseManager.php(317): call_user_func_array(Array, Array)
#6 /data/secret/app/Http/Controllers/SecretApi.php(78): Illuminate\Database\DatabaseManager->__call('select', Array)
#7 [internal function]: App\Http\Controllers\SecretApi->getSecretByHash('asdasd')
#8 /data/secret/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#9 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(603): Illuminate\Container\Container->call(Array, Array)
#10 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(569): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#11 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SecretApi), 'getSecretByHash', Array)
#12 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#13 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#14 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(466): Laravel\Lumen\Application->handleFoundRoute(Array)
#15 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(397): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#16 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#17 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#18 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#19 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#20 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hash' in 'where clause' (SQL: SELECT * FROM secrets where hash = asdasd) in /data/secret/vendor/illuminate/database/Connection.php:729
Stack trace:
#0 /data/secret/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback('SELECT * FROM s...', Array, Object(Closure))
#1 /data/secret/vendor/illuminate/database/Connection.php(349): Illuminate\Database\Connection->run('SELECT * FROM s...', Array, Object(Closure))
#2 [internal function]: Illuminate\Database\Connection->select('SELECT * FROM s...', Array)
#3 /data/secret/vendor/illuminate/database/DatabaseManager.php(317): call_user_func_array(Array, Array)
#4 /data/secret/app/Http/Controllers/SecretApi.php(78): Illuminate\Database\DatabaseManager->__call('select', Array)
#5 [internal function]: App\Http\Controllers\SecretApi->getSecretByHash('asdasd')
#6 /data/secret/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#7 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(603): Illuminate\Container\Container->call(Array, Array)
#8 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(569): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#9 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SecretApi), 'getSecretByHash', Array)
#10 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#11 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#12 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(466): Laravel\Lumen\Application->handleFoundRoute(Array)
#13 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(397): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#14 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#15 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#16 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#17 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#18 {main}  
[2021-03-19 12:54:41] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'App\Http\Controllers\Secret' not found in /data/secret/app/Http/Controllers/SecretApi.php:77
Stack trace:
#0 [internal function]: App\Http\Controllers\SecretApi->getSecretByHash('abcd3')
#1 /data/secret/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#2 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(603): Illuminate\Container\Container->call(Array, Array)
#3 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(569): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#4 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SecretApi), 'getSecretByHash', Array)
#5 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#6 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#7 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(466): Laravel\Lumen\Application->handleFoundRoute(Array)
#8 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(397): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#9 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#10 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#11 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#12 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#13 {main}  
[2021-03-19 12:59:00] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined function App\Http\Controllers\datetime() in /data/secret/app/Http/Controllers/SecretApi.php:91
Stack trace:
#0 [internal function]: App\Http\Controllers\SecretApi->getSecretByHash('abcd')
#1 /data/secret/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#2 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(603): Illuminate\Container\Container->call(Array, Array)
#3 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(569): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#4 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SecretApi), 'getSecretByHash', Array)
#5 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#6 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#7 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(466): Laravel\Lumen\Application->handleFoundRoute(Array)
#8 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(397): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#9 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#10 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#11 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#12 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#13 {main}  
[2021-03-19 12:59:31] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined function DateTime() in /data/secret/app/Http/Controllers/SecretApi.php:91
Stack trace:
#0 [internal function]: App\Http\Controllers\SecretApi->getSecretByHash('abcd')
#1 /data/secret/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#2 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(603): Illuminate\Container\Container->call(Array, Array)
#3 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(569): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#4 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SecretApi), 'getSecretByHash', Array)
#5 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#6 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#7 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(466): Laravel\Lumen\Application->handleFoundRoute(Array)
#8 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(397): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#9 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#10 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#11 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#12 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#13 {main}  
[2021-03-19 12:59:33] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined function DateTime() in /data/secret/app/Http/Controllers/SecretApi.php:91
Stack trace:
#0 [internal function]: App\Http\Controllers\SecretApi->getSecretByHash('abcd')
#1 /data/secret/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#2 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(603): Illuminate\Container\Container->call(Array, Array)
#3 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(569): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#4 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SecretApi), 'getSecretByHash', Array)
#5 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#6 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#7 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(466): Laravel\Lumen\Application->handleFoundRoute(Array)
#8 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(397): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#9 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#10 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#11 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#12 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#13 {main}  
[2021-03-19 12:59:39] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Parse error: syntax error, unexpected '/' in /data/secret/app/Http/Controllers/SecretApi.php:91
Stack trace:
#0 /data/secret/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile('/data/secret/ve...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Http\\Contro...')
#2 [internal function]: spl_autoload_call('App\\Http\\Contro...')
#3 /data/secret/vendor/illuminate/container/Container.php(734): ReflectionClass->__construct('App\\Http\\Contro...')
#4 /data/secret/vendor/illuminate/container/Container.php(629): Illuminate\Container\Container->build('App\\Http\\Contro...', Array)
#5 /data/secret/vendor/laravel/lumen-framework/src/Application.php(206): Illuminate\Container\Container->make('App\\Http\\Contro...', Array)
#6 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(538): Laravel\Lumen\Application->make('App\\Http\\Contro...')
#7 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#8 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#9 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(466): Laravel\Lumen\Application->handleFoundRoute(Array)
#10 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(397): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#11 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#12 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#13 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#14 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#15 {main}  
[2021-03-19 12:59:45] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined function DateTime() in /data/secret/app/Http/Controllers/SecretApi.php:91
Stack trace:
#0 [internal function]: App\Http\Controllers\SecretApi->getSecretByHash('abcd')
#1 /data/secret/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#2 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(603): Illuminate\Container\Container->call(Array, Array)
#3 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(569): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#4 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SecretApi), 'getSecretByHash', Array)
#5 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#6 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#7 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(466): Laravel\Lumen\Application->handleFoundRoute(Array)
#8 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(397): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#9 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#10 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#11 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#12 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#13 {main}  
[2021-03-19 13:08:39] lumen.ERROR: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list' in /data/secret/vendor/illuminate/database/Connection.php:478
Stack trace:
#0 /data/secret/vendor/illuminate/database/Connection.php(478): PDO->prepare('update `secrets...')
#1 /data/secret/vendor/illuminate/database/Connection.php(722): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'update `secrets...', Array)
#2 /data/secret/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback('update `secrets...', Array, Object(Closure))
#3 /data/secret/vendor/illuminate/database/Connection.php(483): Illuminate\Database\Connection->run('update `secrets...', Array, Object(Closure))
#4 /data/secret/vendor/illuminate/database/Connection.php(426): Illuminate\Database\Connection->affectingStatement('update `secrets...', Array)
#5 /data/secret/vendor/illuminate/database/Query/Builder.php(2123): Illuminate\Database\Connection->update('update `secrets...', Array)
#6 /data/secret/vendor/illuminate/database/Eloquent/Builder.php(532): Illuminate\Database\Query\Builder->update(Array)
#7 /data/secret/vendor/illuminate/database/Eloquent/Model.php(1562): Illuminate\Database\Eloquent\Builder->update(Array)
#8 /data/secret/vendor/illuminate/database/Eloquent/Model.php(1481): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder), Array)
#9 /data/secret/app/Http/Controllers/SecretApi.php(86): Illuminate\Database\Eloquent\Model->save()
#10 [internal function]: App\Http\Controllers\SecretApi->getSecretByHash('abcd')
#11 /data/secret/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#12 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(603): Illuminate\Container\Container->call(Array, Array)
#13 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(569): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#14 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SecretApi), 'getSecretByHash', Array)
#15 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#16 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#17 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(466): Laravel\Lumen\Application->handleFoundRoute(Array)
#18 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(397): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#19 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#20 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#21 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#22 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#23 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list' (SQL: update `secrets` set `remainingViews` = 1, `updated_at` = 2021-03-19 13:08:39 where `id` = 1) in /data/secret/vendor/illuminate/database/Connection.php:729
Stack trace:
#0 /data/secret/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback('update `secrets...', Array, Object(Closure))
#1 /data/secret/vendor/illuminate/database/Connection.php(483): Illuminate\Database\Connection->run('update `secrets...', Array, Object(Closure))
#2 /data/secret/vendor/illuminate/database/Connection.php(426): Illuminate\Database\Connection->affectingStatement('update `secrets...', Array)
#3 /data/secret/vendor/illuminate/database/Query/Builder.php(2123): Illuminate\Database\Connection->update('update `secrets...', Array)
#4 /data/secret/vendor/illuminate/database/Eloquent/Builder.php(532): Illuminate\Database\Query\Builder->update(Array)
#5 /data/secret/vendor/illuminate/database/Eloquent/Model.php(1562): Illuminate\Database\Eloquent\Builder->update(Array)
#6 /data/secret/vendor/illuminate/database/Eloquent/Model.php(1481): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder), Array)
#7 /data/secret/app/Http/Controllers/SecretApi.php(86): Illuminate\Database\Eloquent\Model->save()
#8 [internal function]: App\Http\Controllers\SecretApi->getSecretByHash('abcd')
#9 /data/secret/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#10 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(603): Illuminate\Container\Container->call(Array, Array)
#11 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(569): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#12 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SecretApi), 'getSecretByHash', Array)
#13 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#14 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#15 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(466): Laravel\Lumen\Application->handleFoundRoute(Array)
#16 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(397): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#17 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#18 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#19 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#20 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#21 {main}  
[2021-03-19 13:27:01] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Parse error: syntax error, unexpected ';', expecting ')' in /data/secret/app/Http/Controllers/SecretApi.php:66
Stack trace:
#0 /data/secret/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile('/data/secret/ve...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Http\\Contro...')
#2 [internal function]: spl_autoload_call('App\\Http\\Contro...')
#3 /data/secret/vendor/illuminate/container/Container.php(734): ReflectionClass->__construct('App\\Http\\Contro...')
#4 /data/secret/vendor/illuminate/container/Container.php(629): Illuminate\Container\Container->build('App\\Http\\Contro...', Array)
#5 /data/secret/vendor/laravel/lumen-framework/src/Application.php(206): Illuminate\Container\Container->make('App\\Http\\Contro...', Array)
#6 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(538): Laravel\Lumen\Application->make('App\\Http\\Contro...')
#7 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#8 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#9 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(393): Laravel\Lumen\Application->handleFoundRoute(Array)
#10 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#11 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#12 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#13 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#14 {main}  
[2021-03-19 13:27:34] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Method App\Secret::__toString() must return a string value in /data/secret/app/Http/Controllers/SecretApi.php:66
Stack trace:
#0 /data/secret/app/Http/Controllers/SecretApi.php(66): md5(Object(App\Secret))
#1 [internal function]: App\Http\Controllers\SecretApi->addSecret()
#2 /data/secret/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#3 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(603): Illuminate\Container\Container->call(Array, Array)
#4 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(569): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#5 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SecretApi), 'addSecret', Array)
#6 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#7 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#8 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(393): Laravel\Lumen\Application->handleFoundRoute(Array)
#9 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#10 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#11 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#12 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#13 {main}  
[2021-03-19 13:28:02] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Method App\Secret::__toString() must return a string value in /data/secret/app/Http/Controllers/SecretApi.php:66
Stack trace:
#0 /data/secret/app/Http/Controllers/SecretApi.php(66): md5(Object(App\Secret))
#1 [internal function]: App\Http\Controllers\SecretApi->addSecret()
#2 /data/secret/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#3 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(603): Illuminate\Container\Container->call(Array, Array)
#4 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(569): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#5 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SecretApi), 'addSecret', Array)
#6 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#7 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#8 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(393): Laravel\Lumen\Application->handleFoundRoute(Array)
#9 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#10 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#11 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#12 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#13 {main}  
[2021-03-19 13:32:33] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Method App\Secret::__toString() must return a string value in /data/secret/vendor/illuminate/support/helpers.php:747
Stack trace:
#0 /data/secret/vendor/illuminate/support/helpers.php(747): preg_replace('/\\?/', Object(App\Secret), 'insert into `se...', 1)
#1 /data/secret/vendor/illuminate/database/QueryException.php(56): str_replace_array('\\?', Array, 'insert into `se...')
#2 /data/secret/vendor/illuminate/database/QueryException.php(39): Illuminate\Database\QueryException->formatMessage('insert into `se...', Array, Object(PDOException))
#3 /data/secret/vendor/illuminate/database/Connection.php(730): Illuminate\Database\QueryException->__construct('insert into `se...', Array, Object(PDOException))
#4 /data/secret/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback('insert into `se...', Array, Object(Closure))
#5 /data/secret/vendor/illuminate/database/Connection.php(458): Illuminate\Database\Connection->run('insert into `se...', Array, Object(Closure))
#6 /data/secret/vendor/illuminate/database/Connection.php(414): Illuminate\Database\Connection->statement('insert into `se...', Array)
#7 /data/secret/vendor/illuminate/database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `se...', Array)
#8 /data/secret/vendor/illuminate/database/Query/Builder.php(2107): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `se...', Array, 'id')
#9 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#10 /data/secret/vendor/illuminate/database/Eloquent/Builder.php(1423): call_user_func_array(Array, Array)
#11 /data/secret/vendor/illuminate/database/Eloquent/Model.php(1628): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#12 /data/secret/vendor/illuminate/database/Eloquent/Model.php(1597): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#13 /data/secret/vendor/illuminate/database/Eloquent/Model.php(1488): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#14 /data/secret/app/Http/Controllers/SecretApi.php(66): Illuminate\Database\Eloquent\Model->save()
#15 [internal function]: App\Http\Controllers\SecretApi->addSecret()
#16 /data/secret/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#17 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(603): Illuminate\Container\Container->call(Array, Array)
#18 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(569): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#19 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SecretApi), 'addSecret', Array)
#20 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#21 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#22 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(393): Laravel\Lumen\Application->handleFoundRoute(Array)
#23 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#24 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#25 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#26 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#27 {main}  
[2021-03-19 13:37:11] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Method App\Secret::__toString() must return a string value in /data/secret/vendor/illuminate/support/helpers.php:747
Stack trace:
#0 /data/secret/vendor/illuminate/support/helpers.php(747): preg_replace('/\\?/', Object(App\Secret), 'insert into `se...', 1)
#1 /data/secret/vendor/illuminate/database/QueryException.php(56): str_replace_array('\\?', Array, 'insert into `se...')
#2 /data/secret/vendor/illuminate/database/QueryException.php(39): Illuminate\Database\QueryException->formatMessage('insert into `se...', Array, Object(PDOException))
#3 /data/secret/vendor/illuminate/database/Connection.php(730): Illuminate\Database\QueryException->__construct('insert into `se...', Array, Object(PDOException))
#4 /data/secret/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback('insert into `se...', Array, Object(Closure))
#5 /data/secret/vendor/illuminate/database/Connection.php(458): Illuminate\Database\Connection->run('insert into `se...', Array, Object(Closure))
#6 /data/secret/vendor/illuminate/database/Connection.php(414): Illuminate\Database\Connection->statement('insert into `se...', Array)
#7 /data/secret/vendor/illuminate/database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `se...', Array)
#8 /data/secret/vendor/illuminate/database/Query/Builder.php(2107): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `se...', Array, 'id')
#9 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#10 /data/secret/vendor/illuminate/database/Eloquent/Builder.php(1423): call_user_func_array(Array, Array)
#11 /data/secret/vendor/illuminate/database/Eloquent/Model.php(1628): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#12 /data/secret/vendor/illuminate/database/Eloquent/Model.php(1597): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#13 /data/secret/vendor/illuminate/database/Eloquent/Model.php(1488): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#14 /data/secret/app/Http/Controllers/SecretApi.php(66): Illuminate\Database\Eloquent\Model->save()
#15 [internal function]: App\Http\Controllers\SecretApi->addSecret()
#16 /data/secret/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#17 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(603): Illuminate\Container\Container->call(Array, Array)
#18 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(569): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#19 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SecretApi), 'addSecret', Array)
#20 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#21 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#22 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(393): Laravel\Lumen\Application->handleFoundRoute(Array)
#23 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#24 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#25 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#26 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#27 {main}  
[2021-03-19 13:38:22] lumen.ERROR: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'created_at' in 'field list' in /data/secret/vendor/illuminate/database/Connection.php:457
Stack trace:
#0 /data/secret/vendor/illuminate/database/Connection.php(457): PDO->prepare('insert into `se...')
#1 /data/secret/vendor/illuminate/database/Connection.php(722): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `se...', Array)
#2 /data/secret/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback('insert into `se...', Array, Object(Closure))
#3 /data/secret/vendor/illuminate/database/Connection.php(458): Illuminate\Database\Connection->run('insert into `se...', Array, Object(Closure))
#4 /data/secret/vendor/illuminate/database/Connection.php(414): Illuminate\Database\Connection->statement('insert into `se...', Array)
#5 /data/secret/vendor/illuminate/database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `se...', Array)
#6 /data/secret/vendor/illuminate/database/Query/Builder.php(2107): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `se...', Array, 'id')
#7 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#8 /data/secret/vendor/illuminate/database/Eloquent/Builder.php(1423): call_user_func_array(Array, Array)
#9 /data/secret/vendor/illuminate/database/Eloquent/Model.php(1628): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#10 /data/secret/vendor/illuminate/database/Eloquent/Model.php(1597): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 /data/secret/vendor/illuminate/database/Eloquent/Model.php(1488): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#12 /data/secret/app/Http/Controllers/SecretApi.php(66): Illuminate\Database\Eloquent\Model->save()
#13 [internal function]: App\Http\Controllers\SecretApi->addSecret()
#14 /data/secret/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#15 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(603): Illuminate\Container\Container->call(Array, Array)
#16 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(569): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#17 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SecretApi), 'addSecret', Array)
#18 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#19 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#20 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(393): Laravel\Lumen\Application->handleFoundRoute(Array)
#21 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#22 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#23 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#24 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#25 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'created_at' in 'field list' (SQL: insert into `secrets` (`secretText`, `remainingViews`, `expiresAt`, `updated_at`, `created_at`) values (teszt, 15, 2021-03-29 13:20:54, 2021-03-19 13:38:22, 2021-03-19 13:38:22)) in /data/secret/vendor/illuminate/database/Connection.php:729
Stack trace:
#0 /data/secret/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback('insert into `se...', Array, Object(Closure))
#1 /data/secret/vendor/illuminate/database/Connection.php(458): Illuminate\Database\Connection->run('insert into `se...', Array, Object(Closure))
#2 /data/secret/vendor/illuminate/database/Connection.php(414): Illuminate\Database\Connection->statement('insert into `se...', Array)
#3 /data/secret/vendor/illuminate/database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `se...', Array)
#4 /data/secret/vendor/illuminate/database/Query/Builder.php(2107): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `se...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /data/secret/vendor/illuminate/database/Eloquent/Builder.php(1423): call_user_func_array(Array, Array)
#7 /data/secret/vendor/illuminate/database/Eloquent/Model.php(1628): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 /data/secret/vendor/illuminate/database/Eloquent/Model.php(1597): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#9 /data/secret/vendor/illuminate/database/Eloquent/Model.php(1488): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 /data/secret/app/Http/Controllers/SecretApi.php(66): Illuminate\Database\Eloquent\Model->save()
#11 [internal function]: App\Http\Controllers\SecretApi->addSecret()
#12 /data/secret/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#13 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(603): Illuminate\Container\Container->call(Array, Array)
#14 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(569): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#15 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SecretApi), 'addSecret', Array)
#16 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(511): Laravel\Lumen\Application->callControllerAction(Array)
#17 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(496): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#18 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(393): Laravel\Lumen\Application->handleFoundRoute(Array)
#19 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#20 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#21 /data/secret/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(340): Laravel\Lumen\Application->dispatch(NULL)
#22 /data/secret/public/index.php(34): Laravel\Lumen\Application->run()
#23 {main}  
